name: geocat-viz-tutorial
channels:
  - conda-forge
  - ncar
dependencies:
  - python=3.8.10
  - geocat-datafiles
  - matplotlib
  - jupyterlab>=3
  - xarray
  - ipywidgets
  - ffmpeg
  - cmaps
  - cartopy
  - pip
  - pip:
    - git+https://github.com/anissa111/geocat-viz@main
