name: geocat-viz-tutorial
channels:
  - anissa111
  - conda-forge
  - ncar
dependencies:
  - python=3.8.10
  - geocat-viz
  - geocat-datafiles
  - matplotlib
  - jupyterlab>=3
  - xarray
  - ipywidgets
  - ffmpeg